services:
  nextjs:
    image: node:18-alpine
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env # Loads environment variables from .env file
    command: sh -c "npm install --legacy-peer-deps && npm run build && npm start"
    restart: unless-stopped

volumes:
  node_modules:
